### PR TITLE
Add karma testing through Sauce Labs

### PR DESCRIPTION
**Pull request by nomego**
Test goes from ~1s to ~1min :(
Most configurations doesn't seem to work :(

Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>

### CODE REVIEW

**Comment by nomego** [comment]
Edge:
```
2019-10-01T07:13:20.5734638Z [32m01 10 2019 07:13:20.572:INFO [SaucelabsLauncher]: [39mMicrosoftEdge session at https://saucelabs.com/tests/33acc022d4fa42378fc4cd1d670d9a1e
2019-10-01T07:13:22.1709188Z [32m01 10 2019 07:13:22.170:INFO [Edge 18.17763.0 (Windows 10.0.0)]: [39mConnected on socket MB_YX_KMPfLItIGsAAAD with id 23670539
2019-10-01T07:13:25.4942141Z Edge 18.17763.0 (Windows 10.0.0) ERROR: 'failed to load element http://localhost:9876/base/test/cosmoz-treenode.test.js?2ce5e16198895f8e7b00580e42c234a195fd5e29'
2019-10-01T07:13:25.4944054Z Edge 18.17763.0 (Windows 10.0.0) ERROR: 'failed to load element http://localhost:9876/base/test/cosmoz-treenode.test.js?2ce5e16198895f8e7b00580e42c234a195fd5e29'
2019-10-01T07:13:25.6775801Z Edge 18.17763.0 (Windows 10.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
2019-10-01T07:13:25.6778015Z [91m01 10 2019 07:13:25.677:ERROR [reporter.sauce]: [39mâœ– Tests errored
```

Safari:
```
2019-10-01T07:13:30.3570290Z [91m01 10 2019 07:13:30.356:ERROR [SaucelabsLauncher]: [39m{ WebDriverError: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
2019-10-01T07:13:30.3571733Z For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
2019-10-01T07:13:30.3572821Z     at Object.checkLegacyResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/error.js:585:15)
2019-10-01T07:13:30.3573920Z     at parseHttpResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:554:13)
2019-10-01T07:13:30.3575952Z     at Executor.execute (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:489:26)
2019-10-01T07:13:30.3577165Z     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'WebDriverError', remoteStacktrace: '' }
2019-10-01T07:13:30.3581337Z [32m01 10 2019 07:13:30.356:INFO [launcher]: [39mTrying to start safari on SauceLabs again (1/2).
2019-10-01T07:13:55.7754190Z [91m01 10 2019 07:13:55.774:ERROR [SaucelabsLauncher]: [39m{ WebDriverError: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
2019-10-01T07:13:55.7755593Z For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
2019-10-01T07:13:55.7756595Z     at Object.checkLegacyResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/error.js:585:15)
2019-10-01T07:13:55.7757606Z     at parseHttpResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:554:13)
2019-10-01T07:13:55.7758695Z     at Executor.execute (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:489:26)
2019-10-01T07:13:55.7759559Z     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'WebDriverError', remoteStacktrace: '' }
2019-10-01T07:13:55.7761797Z [32m01 10 2019 07:13:55.775:INFO [launcher]: [39mTrying to start safari on SauceLabs again (2/2).
2019-10-01T07:14:22.9985694Z [91m01 10 2019 07:14:22.997:ERROR [SaucelabsLauncher]: [39m{ WebDriverError: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
2019-10-01T07:14:22.9987317Z For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
2019-10-01T07:14:22.9988856Z     at Object.checkLegacyResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/error.js:585:15)
2019-10-01T07:14:22.9989921Z     at parseHttpResponse (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:554:13)
2019-10-01T07:14:22.9991382Z     at Executor.execute (/home/runner/work/cosmoz-treenode/cosmoz-treenode/node_modules/selenium-webdriver/lib/http.js:489:26)
2019-10-01T07:14:22.9992854Z     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'WebDriverError', remoteStacktrace: '' }
2019-10-01T07:14:22.9994630Z [91m01 10 2019 07:14:22.998:ERROR [launcher]: [39msafari on SauceLabs failed 2 times (failure). Giving up.
2019-10-01T07:14:22.9995104Z 
2019-10-01T07:14:22.9995777Z Finished in 1.285 secs / 0.024 secs @ 07:14:22 GMT+0000 (Coordinated Universal Time)
2019-10-01T07:14:22.9996125Z 
2019-10-01T07:14:22.9996536Z SUMMARY:
2019-10-01T07:14:22.9997386Z âœ” 24 tests completed
```

**Comment by cristinecula** [comment]
@nomego you should edit the commit message so it passes commitlint

**Comment by nomego** [comment]
@cristinecula done

**Comment by nomego** [comment]
Haha.. impressed with my interactive rebase? Not sure when I did something like that last :D

**Pull request merged**
